print("Ingrese su primer nombre: ")
Nombre = input()
print("Ingrese su segundo nombre: ")
Nombre2 = input()
print("Ingrese su primer apellido: ")
Ape = input()
print("Ingrese su segundo apellido: ")
Ape2 = input()
print("Ingrese su edad: ")
Edad = input()
print("Ingrese su año de nacimiento: ")
Año = input()
print("Usted se ha registrado como:  " + Nombre + " " + Nombre2 + " " + Ape + " " + Ape2 + " " + "con" + " " + Edad + " " + "años de edad y nacido en el año de: " + Año)
